return {
    ram = {
        ["DEDY"] = {
            size = 16384,
            name = "DEDY Ultra Ram"
        }
    },
    storage = {
        ["pest storage"] = {
            size = 131072,
            name = "Pest Storage"
        }
    },
    motherboards = {
        ["standard motherboard"] = {
            name = "Standard Motherboard",
            slots = {
                ram = 2,
                storage = 1
            }
        }
    },
    GPU = {
        ["basic gpu"] = {
            name = "Basic GPU",
            vram = 2048
        }
    },
    CPU = {
        ["duo core"] = {
            name = "Duo Core",
            cores = 2,
            frequency = 2.5,
            type = "x86_64"
        }
    }
}